export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const EMPLOYEE  = 'EMPLOYEE';
export const GET_EMPLOYEES_BY_COMPANY_SUCCESS = 'GET_EMPLOYEES_BY_COMPANY_SUCCESS';
export const GET_EMPLOYEES_BY_COMPANY_ERROR  = 'GET_EMPLOYEES_BY_COMPANY_ERROR';